language: python # => 1

python: # => 2
      - "2.7" 
      - "3.6"

services: # => 3
      - mysql

env: # => 4
      -DJANGO=1.8 DB=mysql

install: # => 5
      - pip install -r polls/requirements.txt

before_script: # => 6
      - mysql -e 'create database test;' -u root
    
addons:
  sonarcloud:
    organization: "giantpanda0090-github"
    token: $SONAR_TOKEN
    github_token: $GITHUB_TOKEN
    
script:
  - python manage.py test
  - sonar-scanner
