# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-20 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allowed_course_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Related_assignment_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_id', models.IntegerField()),
                ('assignment_id_beta', models.IntegerField()),
                ('assignment_id_thesis', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='U_1data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id_install', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Allowed_course_id')),
                ('related_assignment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Related_assignment_id')),
            ],
        ),
        migrations.AddField(
            model_name='related_assignment_id',
            name='course_id_install',
            field=models.ManyToManyField(through='polls.U_1data', to='polls.Allowed_course_id'),
        ),
    ]
