# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-20 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180520_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowed_course_id',
            name='course_id_install',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
